[package]
name = "module"
version = "0.1.0"
edition = "2021"

[features]
bindgen = ["rquickjs/bindgen"]

[dependencies]
rquickjs = { version = "0.6", features = [
  "array-buffer",
  "either",
  "macro",
  "futures",
], default-features = false }